name: Processar Dados e Publicar Painel

on:
  push:
    branches:
      - main
    paths:
      - 'painel-pcm/Backend/raw_data/**.xlsx'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Construir e Gerar Dados
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependências do Backend
        run: pip install -r painel-pcm/Backend/requirements.txt


      - name: Executar script de processamento de dados
        run: python painel-pcm/Backend/scripts/process_data.py

      - name: Configurar Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependências do Frontend
        run: npm ci
        working-directory: ./painel-pcm/Frontend

      - name: Construir o React App
        run: npm run build
        working-directory: ./painel-pcm/Frontend

      - name: Fazer upload do artefato para o Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./painel-pcm/Frontend/dist

  deploy:
    name: Publicar no GitHub Pages
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Publicar no GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4